baseURL = 'https://harryd97.github.io/'
title = "Harry's Blog"

# Language configuration
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

# Analytics - Uncomment and add your tracking IDs
# googleAnalytics = "G-XXXXXXXXXX"  # Google Analytics 4
# [services.googleAnalytics]
#   id = "G-XXXXXXXXXX"

# Enable search functionality
enableRobotsTXT = true

# Pagination
[pagination]
  pagerSize = 5
buildDrafts = false
buildFuture = false
buildExpired = false
enableEmoji = true
pygmentsUseClasses = true

# Multilingual configuration
[languages]
  [languages.en]
    languageCode = "en-US"
    languageName = "English"
    title = "Harry's Blog"
    weight = 1
    [languages.en.params]
      description = "A modern bilingual blog sharing tech insights and life experiences."
    
  [languages.zh]
    languageCode = "zh-CN"
    languageName = "中文"
    title = "Harry 的博客"
    weight = 2
    [languages.zh.params]
      description = "一个现代化的双语博客，分享技术见解和生活感悟。"

# Theme
theme = "PaperMod"

# Site parameters
[params]
  author = "Harry"
  # PaperMod theme parameters
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true
  disableSpecial1stPost = false
  disableScrollToTop = false
  comments = false
  hidemeta = false
  hideSummary = false
  showtoc = false
  tocopen = false

  # Analytics (replace with your tracking ID)
  # googleAnalytics = "G-XXXXXXXXXX"  # Uncomment and add your GA4 ID
  
  # Search
  [params.fuseOpts]
    isCaseSensitive = false
    shouldSort = true
    location = 0
    distance = 1000
    threshold = 0.4
    minMatchCharLength = 0
    keys = ["title", "permalink", "summary", "content"]

  # Social media links
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/harryd97"

  # [[params.socialIcons]]
  #   name = "twitter"
  #   url = "https://twitter.com/your_twitter"

  # [[params.socialIcons]]
  #   name = "linkedin"
  #   url = "https://linkedin.com/in/your_linkedin"

# Menu configuration
[languages.en.menu]
  [[languages.en.menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[languages.en.menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2
  [[languages.en.menu.main]]
    name = "About"
    url = "/about/"
    weight = 3
  [[languages.en.menu.main]]
    name = "Search"
    url = "/search/"
    weight = 4

[languages.zh.menu]
  [[languages.zh.menu.main]]
    name = "首页"
    url = "/"
    weight = 1
  [[languages.zh.menu.main]]
    name = "文章"
    url = "/posts/"
    weight = 2
  [[languages.zh.menu.main]]
    name = "关于"
    url = "/about/"
    weight = 3
  [[languages.zh.menu.main]]
    name = "搜索"
    url = "/search/"
    weight = 4

# Build configuration
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
