baseURL = 'https://harryd97.github.io/'
title = "Harry's Blog"

# Language configuration
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

# Analytics - Uncomment and add your tracking IDs
# googleAnalytics = "G-XXXXXXXXXX"  # Google Analytics 4
# [services.googleAnalytics]
#   id = "G-XXXXXXXXXX"

# Enable search functionality
enableRobotsTXT = true

# Pagination
[pagination]
  pagerSize = 5
buildDrafts = false
buildFuture = false
buildExpired = false
enableEmoji = true
pygmentsUseClasses = true

# Multilingual configuration
[languages]
  [languages.en]
    languageCode = "en-US"
    languageName = "English"
    title = "Harry's Blog"
    weight = 1
    [languages.en.params]
      description = "A modern bilingual blog sharing tech insights and life experiences."
    
  [languages.zh]
    languageCode = "zh-CN"
    languageName = "中文"
    title = "Harry 的博客"
    weight = 2
    [languages.zh.params]
      description = "一个现代化的双语博客，分享技术见解和生活感悟。"

# Theme
theme = "hextra"

# Site parameters
[params]
  author = "Harry"
  
  # Hextra theme parameters
  [params.theme]
    default = "system"
    displayToggle = true
  
  [params.navbar]
    displayLogo = true
    width = "wide"
  
  [params.search]
    enable = true
    type = "flexsearch"
  
  [params.editPage]
    enable = false

# Menu configuration
[languages.en.menu]
  [[languages.en.menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[languages.en.menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2
  [[languages.en.menu.main]]
    name = "About"
    url = "/about/"
    weight = 3
  [[languages.en.menu.main]]
    name = "Search"
    url = "/search/"
    weight = 4

[languages.zh.menu]
  [[languages.zh.menu.main]]
    name = "首页"
    url = "/"
    weight = 1
  [[languages.zh.menu.main]]
    name = "文章"
    url = "/posts/"
    weight = 2
  [[languages.zh.menu.main]]
    name = "关于"
    url = "/about/"
    weight = 3
  [[languages.zh.menu.main]]
    name = "搜索"
    url = "/search/"
    weight = 4

# Build configuration
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
